using System.Reflection;
using System.Runtime.InteropServices;

namespace WpfGfxShape.ComAcceptance;

[TestClass]
[DoNotParallelize]
public sealed unsafe partial class CompositionTests
{
    [TestMethod]
    [DataRow(false, false)]
    [DataRow(true, false)]
    [DataRow(false, true)]
    public void WhenCopyForwardIsComposedThenVisualDrawImageConsumesFrontBufferAcrossFrames(bool failWithLockedTarget, bool removeRootChannel)
    {
        string path = typeof(CompositionTests).Assembly.GetCustomAttributes<AssemblyMetadataAttribute>().Single(a => a.Key == "AotDllPath").Value!;
        nint module = NativeLibrary.Load(path);
        var present = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "WgxConnection_SameThreadPresent");
        var createConnection = (delegate* unmanaged[Stdcall]<byte, nint*, int>)NativeLibrary.GetExport(module, "WgxConnection_Create");
        var disconnect = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "WgxConnection_Disconnect");
        var createChannel = (delegate* unmanaged[Stdcall]<nint, nint, nint*, int>)NativeLibrary.GetExport(module, "MilConnection_CreateChannel");
        var destroyChannel = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "MilConnection_DestroyChannel");
        var createResource = (delegate* unmanaged[Stdcall]<nint, uint, uint*, int>)NativeLibrary.GetExport(module, "MilResource_CreateOrAddRefOnChannel");
        var send = (delegate* unmanaged[Stdcall]<void*, uint, byte, nint, int>)NativeLibrary.GetExport(module, "MilResource_SendCommand");
        var close = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "MilChannel_CloseBatch");
        var commit = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "MilChannel_CommitChannel");
        var createFactory = (delegate* unmanaged[Stdcall]<nint*, uint, int>)NativeLibrary.GetExport(module, "MILCreateFactory");
        var createTarget = (delegate* unmanaged[Stdcall]<nint, uint, uint, uint, float, float, uint, nint*, int>)NativeLibrary.GetExport(module, "MILFactoryCreateBitmapRenderTarget");
        var getBitmap = (delegate* unmanaged[Stdcall]<nint, nint*, int>)NativeLibrary.GetExport(module, "MILRenderTargetBitmapGetBitmap");
        var createDouble = (delegate* unmanaged[Stdcall]<uint, uint, double, double, Guid*, nint, nint*, int>)NativeLibrary.GetExport(module, "MILSwDoubleBufferedBitmapCreate");
        var backBuffer = (delegate* unmanaged[Stdcall]<nint, nint*, uint*, int>)NativeLibrary.GetExport(module, "MILSwDoubleBufferedBitmapGetBackBuffer");
        var dirty = (delegate* unmanaged[Stdcall]<nint, int*, int>)NativeLibrary.GetExport(module, "MILSwDoubleBufferedBitmapAddDirtyRect");
        var protect = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "MILSwDoubleBufferedBitmapProtectBackBuffer");
        using var wic = new SystemWicBitmap();
        nint connection = 0, channel = 0, factory = 0, target = 0, owner = 0, back = 0, output = 0;
        try
        {
            Assert.AreEqual(0, createConnection(1, &connection));
            Assert.AreEqual(0, createChannel(connection, 0, &channel));
            Assert.AreEqual(0, createFactory(&factory, 0x200184C0));
            output = wic.Create(2, 1);
            var createExisting = (delegate* unmanaged[Stdcall]<nint, nint, nint*, int>)NativeLibrary.GetExport(module, "MILFactoryCreateSWRenderTargetForBitmap");
            Assert.AreEqual(0, createExisting(factory, output, &target));
            Guid format = new("6fddc324-4e03-4bfe-b185-3d77768dc910");
            Assert.AreEqual(0, createDouble(2, 1, 96, 96, &format, 0, &owner));
            uint size = 0;
            Assert.AreEqual(0, backBuffer(owner, &back, &size));
            uint image = 0, data = 0, visual = 0, destination = 0;
            Assert.AreEqual(0, createResource(channel, 96, &image));
            Assert.AreEqual(0, createResource(channel, 43, &data));
            Assert.AreEqual(0, createResource(channel, 39, &visual));
            Assert.AreEqual(0, createResource(channel, 47, &destination));
            TargetPacket targetPacket = new() { Type = 0x34, Handle = destination, Target = (ulong)target, Width = 2, Height = 1 };
            Assert.AreEqual(0, send(&targetPacket, (uint)sizeof(TargetPacket), 0, channel));
            ImagePacket imagePacket = new() { Type = 0x3b, Handle = image, Bitmap = (ulong)owner };
            ((delegate* unmanaged[Stdcall]<nint, uint>)(*(void***)owner)[1])(owner);
            Assert.AreEqual(0, send(&imagePacket, (uint)sizeof(ImagePacket), 0, channel));
            DrawPacket draw = new() { Type = 0x18, Handle = data, DataSize = 48, RecordSize = 48, Command = 0x47, Width = 2, Height = 1, Image = image };
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            uint* binding = stackalloc uint[] { 0x22, visual, data };
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            binding[0] = 0x35; binding[1] = destination; binding[2] = visual;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Write(back, 0xffff0000, 0xff00ff00);
            int* rect = stackalloc int[] { 0, 0, 2, 1 };
            Assert.AreEqual(0, dirty(owner, rect));
            Assert.AreEqual(0, protect(owner));
            CopyPacket copy = new() { Type = 0x3c, Handle = image };
            Assert.AreEqual(0, send(&copy, (uint)sizeof(CopyPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            uint child = 0;
            Assert.AreEqual(0, createResource(channel, 39, &child));
            binding[0] = 0x22; binding[1] = child; binding[2] = data;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            uint* insert = stackalloc uint[] { 0x26, visual, child, 0 };
            Assert.AreEqual(0, send(insert, 16, 0, channel));
            AlphaPacket alpha = new() { Type = 0x20, Handle = visual, Alpha = 0.5 };
            Assert.AreEqual(0, send(&alpha, (uint)sizeof(AlphaPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            alpha.Handle = child;
            Assert.AreEqual(0, send(&alpha, (uint)sizeof(AlphaPacket), 0, channel));
            binding[0] = 0x22; binding[1] = visual; binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff4000bfu, 0xff0040bfu), Read(output));
            uint* removeChildren = stackalloc uint[] { 0x24, visual };
            Assert.AreEqual(0, send(removeChildren, 8, 0, channel));
            alpha.Handle = visual; alpha.Alpha = 1;
            Assert.AreEqual(0, send(&alpha, (uint)sizeof(AlphaPacket), 0, channel));
            binding[0] = 0x22; binding[1] = visual; binding[2] = data;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            byte* layered = stackalloc byte[132];
            new Span<byte>(layered, 132).Clear();
            ((uint*)layered)[0] = 0x18; ((uint*)layered)[1] = data; ((uint*)layered)[2] = 120;
            *(uint*)(layered + 12) = 16; *(uint*)(layered + 16) = 0x4f; *(double*)(layered + 20) = 0.5;
            new ReadOnlySpan<byte>((byte*)&draw + 12, 48).CopyTo(new Span<byte>(layered + 28, 48));
            new ReadOnlySpan<byte>((byte*)&draw + 12, 48).CopyTo(new Span<byte>(layered + 76, 48));
            *(uint*)(layered + 124) = 8; *(uint*)(layered + 128) = 0x56;
            Assert.AreEqual(0, send(layered, 132, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            *(double*)(layered + 84) = double.NaN;
            Assert.AreEqual(0, send(layered, 132, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(unchecked((int)0x80004001), present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint animatedTranslate = 0, animatedY = 0;
            Assert.AreEqual(0, createResource(channel, 62, &animatedTranslate));
            Assert.AreEqual(0, createResource(channel, 49, &animatedY));
            byte* animatedValue = stackalloc byte[16];
            *(uint*)animatedValue = 0x0e; *(uint*)(animatedValue + 4) = animatedY; *(double*)(animatedValue + 8) = 0;
            Assert.AreEqual(0, send(animatedValue, 16, 0, channel));
            byte* translatePacket = stackalloc byte[32];
            new Span<byte>(translatePacket, 32).Clear();
            *(uint*)translatePacket = 0x73; *(uint*)(translatePacket + 4) = animatedTranslate;
            *(double*)(translatePacket + 8) = 1; *(double*)(translatePacket + 16) = 8;
            *(uint*)(translatePacket + 28) = animatedY;
            Assert.AreEqual(0, send(translatePacket, 32, 0, channel));
            binding[0] = 0x1c; binding[1] = visual; binding[2] = animatedTranslate;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0u, 0xffff0000u), Read(output));
            *(double*)(animatedValue + 8) = 1;
            Assert.AreEqual(0, send(animatedValue, 16, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0u, 0u), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            uint animatedRect = 0;
            Assert.AreEqual(0, createResource(channel, 52, &animatedRect));
            byte* rectangleValue = stackalloc byte[40];
            new Span<byte>(rectangleValue, 40).Clear();
            *(uint*)rectangleValue = 0x11; *(uint*)(rectangleValue + 4) = animatedRect;
            *(double*)(rectangleValue + 8) = 1; *(double*)(rectangleValue + 24) = 2; *(double*)(rectangleValue + 32) = 1;
            Assert.AreEqual(0, send(rectangleValue, 40, 0, channel));
            byte* animatedDrawing = stackalloc byte[92];
            new Span<byte>(animatedDrawing, 92).Clear();
            *(uint*)animatedDrawing = 0x18; *(uint*)(animatedDrawing + 4) = data; *(uint*)(animatedDrawing + 8) = 80;
            *(uint*)(animatedDrawing + 12) = 24; *(uint*)(animatedDrawing + 16) = 0x50;
            *(double*)(animatedDrawing + 20) = 0.25; *(uint*)(animatedDrawing + 28) = animatedY;
            new ReadOnlySpan<byte>((byte*)&draw + 12, 48).CopyTo(new Span<byte>(animatedDrawing + 36, 48));
            *(uint*)(animatedDrawing + 40) = 0x48; *(uint*)(animatedDrawing + 80) = animatedRect;
            *(uint*)(animatedDrawing + 84) = 8; *(uint*)(animatedDrawing + 88) = 0x56;
            Assert.AreEqual(0, send(animatedDrawing, 92, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0u, 0xffff0000u), Read(output));
            *(double*)(rectangleValue + 8) = 0;
            *(double*)(animatedValue + 8) = 0.5;
            Assert.AreEqual(0, send(rectangleValue, 40, 0, channel));
            Assert.AreEqual(0, send(animatedValue, 16, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0x80800000u, 0x80008000u), Read(output));
            *(double*)(animatedValue + 8) = double.NaN;
            Assert.AreEqual(0, send(animatedValue, 16, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(unchecked((int)0x80004001), present(connection));
            Assert.AreEqual((0x80800000u, 0x80008000u), Read(output));
            *(uint*)(animatedDrawing + 28) = 0;
            *(uint*)(animatedDrawing + 80) = 0;
            Assert.AreEqual(0, send(animatedDrawing, 92, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0x40400000u, 0x40004000u), Read(output));
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            uint transform = 0;
            Assert.AreEqual(0, createResource(channel, 66, &transform));
            byte* matrix = stackalloc byte[60];
            new Span<byte>(matrix, 60).Clear();
            *(uint*)matrix = 0x77; *(uint*)(matrix + 4) = transform;
            *(double*)(matrix + 8) = 2; *(double*)(matrix + 32) = 1; *(double*)(matrix + 40) = -1;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            binding[0] = 0x1c; binding[1] = visual; binding[2] = transform;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffbf4000u, 0xff40bf00u), Read(output));
            uint* options = stackalloc uint[] { 0x21, visual, 1, 0, 0, 3, 0, 0, 0 };
            Assert.AreEqual(0, send(options, 36, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            alpha.Handle = child; alpha.Alpha = 1;
            Assert.AreEqual(0, send(&alpha, (uint)sizeof(AlphaPacket), 0, channel));
            Assert.AreEqual(0, send(insert, 16, 0, channel));
            options[1] = child; options[5] = 1;
            Assert.AreEqual(0, send(options, 36, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffbf4000u, 0xff40bf00u), Read(output));
            options[5] = 0;
            Assert.AreEqual(0, send(options, 36, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            Assert.AreEqual(0, send(removeChildren, 8, 0, channel));
            options[1] = visual; options[2] = 0;
            Assert.AreEqual(0, send(options, 36, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffbf4000u, 0xff40bf00u), Read(output));
            *(double*)(matrix + 8) = -1;
            *(double*)(matrix + 40) = 2;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff00ff00u, 0xffff0000u), Read(output));
            *(double*)(matrix + 8) = 0; *(double*)(matrix + 16) = 1;
            *(double*)(matrix + 24) = -1; *(double*)(matrix + 32) = 0; *(double*)(matrix + 40) = 1;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0u), Read(output));
            *(double*)(matrix + 8) = 1; *(double*)(matrix + 16) = 0;
            *(double*)(matrix + 24) = 1; *(double*)(matrix + 32) = 1; *(double*)(matrix + 40) = 0;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0x8f8f0000u, 0xff808000u), Read(output));
            *(double*)(matrix + 24) = 0; *(double*)(matrix + 32) = 1;
            *(double*)(matrix + 8) = 2;
            *(double*)(matrix + 40) = -1;
            *(double*)(matrix + 16) = double.NaN;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(unchecked((int)0x80004001), present(connection));
            Assert.AreEqual((0x8f8f0000u, 0xff808000u), Read(output));
            *(double*)(matrix + 16) = 0;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            byte* transformed = stackalloc byte[132];
            new Span<byte>(transformed, 132).Clear();
            *(uint*)transformed = 0x18; *(uint*)(transformed + 4) = data; *(uint*)(transformed + 8) = 120;
            *(uint*)(transformed + 12) = 16; *(uint*)(transformed + 16) = 0x51; *(uint*)(transformed + 20) = transform;
            new ReadOnlySpan<byte>((byte*)&draw + 12, 48).CopyTo(new Span<byte>(transformed + 28, 48));
            *(uint*)(transformed + 76) = 8; *(uint*)(transformed + 80) = 0x56;
            new ReadOnlySpan<byte>((byte*)&draw + 12, 48).CopyTo(new Span<byte>(transformed + 84, 48));
            Assert.AreEqual(0, send(transformed, 132, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint clipGeometry = 0;
            Assert.AreEqual(0, createResource(channel, 69, &clipGeometry));
            byte* clipPacket = stackalloc byte[72];
            new Span<byte>(clipPacket, 72).Clear();
            *(uint*)clipPacket = 0x79; *(uint*)(clipPacket + 4) = clipGeometry;
            *(double*)(clipPacket + 24) = 1; *(double*)(clipPacket + 40) = 1; *(double*)(clipPacket + 48) = 1;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            binding[0] = 0x1f; binding[1] = visual; binding[2] = clipGeometry;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff00ff00u), Read(output));
            *(double*)(rectangleValue + 8) = 0.5;
            *(double*)(rectangleValue + 24) = 1;
            Assert.AreEqual(0, send(rectangleValue, 40, 0, channel));
            *(uint*)(clipPacket + 68) = animatedRect;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            *(double*)(rectangleValue + 8) = 0;
            Assert.AreEqual(0, send(rectangleValue, 40, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff0000ffu), Read(output));
            *(uint*)(clipPacket + 68) = 0;
            *(double*)(clipPacket + 24) = 0.5;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            *(double*)(layered + 84) = 0;
            Assert.AreEqual(0, send(layered, 132, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff4000bfu, 0xff0040bfu), Read(output));
            *(double*)(layered + 84) = double.NaN;
            Assert.AreEqual(0, send(layered, 132, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(unchecked((int)0x80004001), present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            *(double*)(matrix + 8) = 1; *(double*)(matrix + 16) = 0;
            *(double*)(matrix + 24) = 1; *(double*)(matrix + 32) = 1; *(double*)(matrix + 40) = 0;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            *(double*)(clipPacket + 24) = 0;
            *(uint*)(clipPacket + 56) = transform;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff8f0070u, 0xff00708fu), Read(output));
            *(double*)(clipPacket + 24) = 1;
            *(double*)(clipPacket + 40) = -1;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            *(double*)(clipPacket + 40) = 1;
            *(double*)(clipPacket + 32) = 1;
            *(double*)(clipPacket + 48) = -1;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            *(double*)(clipPacket + 32) = 0;
            *(double*)(clipPacket + 48) = 1;
            *(double*)(clipPacket + 40) = 0;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            *(double*)(clipPacket + 40) = 1;
            *(double*)(clipPacket + 48) = 0;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            *(double*)(clipPacket + 48) = 1;
            *(double*)(clipPacket + 24) = 1;
            *(uint*)(clipPacket + 56) = 0;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            *(uint*)(transformed + 16) = 0x4d;
            *(uint*)(transformed + 20) = clipGeometry;
            Assert.AreEqual(0, send(transformed, 132, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            *(double*)(clipPacket + 24) = 0.5;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint combinedClip = 0;
            Assert.AreEqual(0, createResource(channel, 72, &combinedClip));
            uint* combinedPacket = stackalloc uint[] { 0x7c, combinedClip, 0, 1, clipGeometry, clipGeometry };
            Assert.AreEqual(0, send(combinedPacket, 24, 0, channel));
            binding[0] = 0x1f; binding[1] = visual; binding[2] = combinedClip;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            combinedPacket[3] = 0;
            Assert.AreEqual(0, send(combinedPacket, 24, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            combinedPacket[3] = 3;
            Assert.AreEqual(0, send(combinedPacket, 24, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            combinedPacket[5] = 0;
            Assert.AreEqual(0, send(combinedPacket, 24, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            combinedPacket[5] = clipGeometry;
            combinedPacket[3] = 2;
            Assert.AreEqual(0, send(combinedPacket, 24, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint pathClip = 0;
            Assert.AreEqual(0, createResource(channel, 73, &pathClip));
            binding[2] = pathClip;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            byte* pathPacket = stackalloc byte[276];
            new Span<byte>(pathPacket, 276).Clear();
            *(uint*)pathPacket = 0x7d; *(uint*)(pathPacket + 4) = pathClip;
            *(uint*)(pathPacket + 16) = 256;
            *(uint*)(pathPacket + 20) = 256; *(uint*)(pathPacket + 60) = 2;
            byte* figure1 = pathPacket + 68;
            *(uint*)(figure1 + 4) = 12; *(uint*)(figure1 + 8) = 2; *(uint*)(figure1 + 12) = 104; *(uint*)(figure1 + 32) = 72;
            *(uint*)(figure1 + 40) = 1;
            *(double*)(figure1 + 56) = 2; *(double*)(figure1 + 64) = 1;
            *(uint*)(figure1 + 72) = 1; *(uint*)(figure1 + 80) = 32;
            *(double*)(figure1 + 96) = 1;
            byte* figure2 = figure1 + 104;
            new ReadOnlySpan<byte>(figure1, 104).CopyTo(new Span<byte>(figure2, 104));
            *(uint*)figure2 = 104;
            Assert.AreEqual(0, send(pathPacket, 276, 0, channel));
            binding[2] = pathClip;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            *(uint*)(pathPacket + 12) = 1;
            Assert.AreEqual(0, send(pathPacket, 276, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffaf0050u, 0xff0030cfu), Read(output));
            *(uint*)(pathPacket + 16) = 184; *(uint*)(pathPacket + 20) = 184; *(uint*)(pathPacket + 60) = 1;
            *(uint*)(figure1 + 4) = 14; *(uint*)(figure1 + 12) = 136; *(uint*)(figure1 + 32) = 104;
            *(uint*)(figure1 + 40) = 2;
            *(double*)(figure1 + 56) = 0; *(double*)(figure1 + 64) = 0;
            *(double*)(figure1 + 72) = 2; *(double*)(figure1 + 80) = 1;
            *(double*)(figure1 + 88) = 2; *(double*)(figure1 + 96) = 1;
            new Span<byte>(figure1 + 104, 32).Clear();
            *(uint*)(figure1 + 104) = 1; *(uint*)(figure1 + 112) = 64; *(double*)(figure1 + 128) = 1;
            Assert.AreEqual(0, send(pathPacket, 204, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffaf0050u, 0xff0030cfu), Read(output));
            *(uint*)(pathPacket + 16) = 136; *(uint*)(pathPacket + 20) = 136;
            *(uint*)(figure1 + 8) = 1; *(uint*)(figure1 + 12) = 88; *(uint*)(figure1 + 32) = 40;
            *(uint*)(figure1 + 40) = 3;
            *(double*)(figure1 + 56) = 1; *(double*)(figure1 + 64) = 2;
            *(double*)(figure1 + 72) = 2; *(double*)(figure1 + 80) = 0;
            Assert.AreEqual(0, send(pathPacket, 156, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            // Four flattened edges cover 42 and 46 of the 64 subpixel samples.
            Assert.AreEqual((0xffa70058u, 0xff00b748u), Read(output));
            *(uint*)(figure1 + 40) = 7; *(uint*)(figure1 + 52) = 2;
            Assert.AreEqual(0, send(pathPacket, 156, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffa70058u, 0xff00b748u), Read(output));
            *(uint*)(pathPacket + 16) = 152; *(uint*)(pathPacket + 20) = 152;
            *(uint*)(figure1 + 12) = 104; *(uint*)(figure1 + 40) = 2; *(uint*)(figure1 + 52) = 0;
            *(double*)(figure1 + 56) = 2.0 / 3; *(double*)(figure1 + 64) = 4.0 / 3;
            *(double*)(figure1 + 72) = 4.0 / 3; *(double*)(figure1 + 80) = 4.0 / 3;
            *(double*)(figure1 + 88) = 2; *(double*)(figure1 + 96) = 0;
            Assert.AreEqual(0, send(pathPacket, 172, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffa70058u, 0xff00b748u), Read(output));
            *(uint*)(figure1 + 40) = 6; *(uint*)(figure1 + 52) = 3;
            Assert.AreEqual(0, send(pathPacket, 172, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffa70058u, 0xff00b748u), Read(output));
            *(double*)(figure1 + 16) = -9; *(double*)(figure1 + 24) = 0;
            new Span<byte>(figure1 + 40, 64).Clear();
            *(uint*)(figure1 + 40) = 4;
            *(double*)(figure1 + 56) = 11;
            *(double*)(figure1 + 72) = 1; *(double*)(figure1 + 80) = 1;
            Assert.AreEqual(0, send(pathPacket, 172, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            *(uint*)(figure1 + 96) = 1;
            Assert.AreEqual(0, send(pathPacket, 172, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            *(double*)(matrix + 8) = 2000000; *(double*)(matrix + 16) = 0;
            *(double*)(matrix + 24) = 0; *(double*)(matrix + 32) = 2000000; *(double*)(matrix + 40) = 0;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            *(uint*)(pathPacket + 8) = transform;
            *(uint*)(pathPacket + 16) = 184; *(uint*)(pathPacket + 20) = 184;
            *(uint*)(figure1 + 8) = 2; *(uint*)(figure1 + 12) = 136; *(uint*)(figure1 + 32) = 104;
            *(double*)(figure1 + 16) = 0; *(double*)(figure1 + 24) = 0;
            *(double*)(figure1 + 56) = 0.000001; *(double*)(figure1 + 64) = 0;
            new Span<byte>(figure1 + 104, 32).Clear();
            *(uint*)(figure1 + 104) = 1; *(uint*)(figure1 + 112) = 64;
            *(double*)(figure1 + 120) = 0.000001; *(double*)(figure1 + 128) = 0.0000005;
            Assert.AreEqual(0, send(pathPacket, 204, 0, channel));
            binding[2] = pathClip;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff5000afu, 0xff00cf30u), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint geometryGroup = 0;
            Assert.AreEqual(0, createResource(channel, 71, &geometryGroup));
            uint* groupPacket = stackalloc uint[] { 0x7b, geometryGroup, 0, 0, 8, clipGeometry, clipGeometry };
            Assert.AreEqual(0, send(groupPacket, 28, 0, channel));
            binding[2] = geometryGroup;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            groupPacket[3] = 1;
            Assert.AreEqual(0, send(groupPacket, 28, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            uint reversedRect = 0;
            Assert.AreEqual(0, createResource(channel, 69, &reversedRect));
            *(double*)(matrix + 8) = -1; *(double*)(matrix + 16) = 0;
            *(double*)(matrix + 24) = 0; *(double*)(matrix + 32) = 1; *(double*)(matrix + 40) = 2;
            Assert.AreEqual(0, send(matrix, 60, 0, channel));
            *(uint*)(clipPacket + 4) = reversedRect; *(uint*)(clipPacket + 56) = transform;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            groupPacket[6] = reversedRect;
            Assert.AreEqual(0, send(groupPacket, 28, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint ellipseClip = 0;
            Assert.AreEqual(0, createResource(channel, 70, &ellipseClip));
            byte* ellipsePacket = stackalloc byte[56];
            new Span<byte>(ellipsePacket, 56).Clear();
            *(uint*)ellipsePacket = 0x7a; *(uint*)(ellipsePacket + 4) = ellipseClip;
            *(double*)(ellipsePacket + 8) = -10; *(double*)(ellipsePacket + 16) = 10;
            *(double*)(ellipsePacket + 24) = 1; *(double*)(ellipsePacket + 32) = 0.5;
            Assert.AreEqual(0, send(ellipsePacket, 56, 0, channel));
            binding[2] = ellipseClip;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            *(double*)(animatedValue + 8) = 0;
            Assert.AreEqual(0, send(animatedValue, 16, 0, channel));
            *(uint*)(ellipsePacket + 44) = animatedY;
            Assert.AreEqual(0, send(ellipsePacket, 56, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            *(double*)(animatedValue + 8) = 10;
            Assert.AreEqual(0, send(animatedValue, 16, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            *(uint*)(clipPacket + 4) = clipGeometry; *(uint*)(clipPacket + 56) = 0;
            *(double*)(clipPacket + 8) = 100; *(double*)(clipPacket + 16) = 100;
            *(double*)(clipPacket + 24) = -9; *(double*)(clipPacket + 32) = -9.5;
            *(double*)(clipPacket + 40) = 20; *(double*)(clipPacket + 48) = 20;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            binding[2] = clipGeometry;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            *(double*)(clipPacket + 40) = 0;
            Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint lineClip = 0;
            Assert.AreEqual(0, createResource(channel, 68, &lineClip));
            byte* linePacket = stackalloc byte[52];
            new Span<byte>(linePacket, 52).Clear();
            *(uint*)linePacket = 0x78; *(uint*)(linePacket + 4) = lineClip;
            *(double*)(linePacket + 24) = 2; *(double*)(linePacket + 32) = 1;
            Assert.AreEqual(0, send(linePacket, 52, 0, channel));
            binding[2] = lineClip;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
            groupPacket[5] = lineClip; groupPacket[6] = ellipseClip;
            Assert.AreEqual(0, send(groupPacket, 28, 0, channel));
            binding[2] = geometryGroup;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            binding[2] = 0;
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            VerifySharedTarget(connection, channel, visual, factory, output);
            Write(back, 0xff0000ff, 0xffffffff);
            rect[2] = 1;
            Assert.AreEqual(0, dirty(owner, rect));
            Assert.AreEqual(0, protect(owner));
            Assert.AreEqual(0, send(&copy, (uint)sizeof(CopyPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff00ff00u), Read(output));
            if (failWithLockedTarget)
            {
                nint heldLock = 0;
                try
                {
                    Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, nint, uint, nint*, int>)(*(void***)output)[8])(output, 0, 2, &heldLock));
                    Assert.AreEqual(unchecked((int)0x88982F0D), present(connection));
                }
                finally { Release(heldLock); }
                Assert.AreEqual(0, present(connection));
            }
            Write(back, 0x80800000, 0x80008000);
            rect[2] = 2;
            Assert.AreEqual(0, dirty(owner, rect));
            Assert.AreEqual(0, protect(owner));
            Assert.AreEqual(0, send(&copy, (uint)sizeof(CopyPacket), 0, channel));
            Assert.AreEqual(0, close(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff00ff00u), Read(output));
            Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            options[2] = 4; options[4] = 1;
            Assert.AreEqual(0, send(options, 36, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0x80800000u, 0x80008000u), Read(output));
            draw.X = 0.5;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0x40400000u, 0x80404000u), Read(output));
            options[2] = 0; draw.X = 0;
            Assert.AreEqual(0, send(options, 36, 0, channel));
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            draw.X = -1;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff00807fu, 0xff0000ffu), Read(output));
            draw.X = -1;
            draw.Width = 4;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff60207fu, 0xff20607fu), Read(output));
            draw.X = 0;
            draw.Width = 2;
            draw.Height = 2;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
            draw.Height = 1;
            draw.Width = 1;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0xff0000ff, 0xff0000ff);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff40407fu, 0xff0000ffu), Read(output));
            Write(output, 0xff80007f, 0xff00807f);
            draw.Width = 2;
            draw.X = 0.5;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffa0005fu, 0xff40803fu), Read(output));
            draw.X = 0;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Write(back, 0xff0000ff, 0xff00ff00);
            Assert.AreEqual(0, dirty(owner, rect));
            Assert.AreEqual(0, protect(owner));
            Assert.AreEqual(0, send(&copy, (uint)sizeof(CopyPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            uint bitmapResource = 0;
            Assert.AreEqual(0, createResource(channel, 95, &bitmapResource));
            BitmapSourcePacket sourcePacket = new() { Type = 0x0c, Handle = bitmapResource, Bitmap = back };
            ((delegate* unmanaged[Stdcall]<nint, uint>)(*(void***)back)[1])(back);
            Assert.AreEqual(0, send(&sourcePacket, (uint)sizeof(BitmapSourcePacket), 0, channel));
            draw.Image = bitmapResource;
            Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Write(output, 0, 0);
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xff0000ffu, 0xff00ff00u), Read(output));
            nint replacementTarget = 0, replacement = 0, sourceLock = 0;
            try
            {
                replacement = wic.Create(2, 1);
                var wrapBitmap = (delegate* unmanaged[Stdcall]<nint, nint*, int>)NativeLibrary.GetExport(module, "MilResource_CreateCWICWrapperBitmap");
                Assert.AreEqual(0, wrapBitmap(replacement, &replacementTarget));
                Release(replacement); replacement = replacementTarget; replacementTarget = 0;
                Write(replacement, 0xffff00ff, 0xff00ffff);
                sourcePacket.Bitmap = replacement;
                ((delegate* unmanaged[Stdcall]<nint, uint>)(*(void***)replacement)[1])(replacement);
                Assert.AreEqual(0, send(&sourcePacket, (uint)sizeof(BitmapSourcePacket), 0, channel));
                Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                Release(replacementTarget); replacementTarget = 0;
                Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, nint, uint, nint*, int>)(*(void***)replacement)[8])(replacement, 0, 2, &sourceLock));
                Assert.AreEqual(unchecked((int)0x88982F0D), present(connection));
                Assert.AreEqual((0xff0000ffu, 0xff00ff00u), Read(output));
                Release(sourceLock); sourceLock = 0;
                Release(replacement); replacement = 0;
                Assert.AreEqual(0, present(connection));
                Assert.AreEqual((0xffff00ffu, 0xff00ffffu), Read(output));
                nint sourceBitmap = 0, sourceOnly = 0, sourceWrapper = 0;
                try
                {
                    sourceBitmap = wic.Create(2, 1);
                    Write(sourceBitmap, 0xff123456, 0xffabcdef);
                    sourceOnly = wic.CreateSource(sourceBitmap);
                    Assert.AreEqual(0, wrapBitmap(sourceOnly, &sourceWrapper));
                    sourcePacket.Bitmap = sourceWrapper;
                    ((delegate* unmanaged[Stdcall]<nint, uint>)(*(void***)sourceWrapper)[1])(sourceWrapper);
                    Assert.AreEqual(0, send(&sourcePacket, (uint)sizeof(BitmapSourcePacket), 0, channel));
                    Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                    Release(sourceWrapper); sourceWrapper = 0;
                    Release(sourceOnly); sourceOnly = 0;
                    Release(sourceBitmap); sourceBitmap = 0;
                    Write(output, 0, 0);
                    Assert.AreEqual(0, present(connection));
                    Assert.AreEqual((0xff123456u, 0xffabcdefu), Read(output));
                }
                finally { Release(sourceWrapper); Release(sourceOnly); Release(sourceBitmap); }
                nint straightOwner = 0, straight = 0;
                try
                {
                    Guid straightFormat = new("6fddc324-4e03-4bfe-b185-3d77768dc90f");
                    Assert.AreEqual(0, createDouble(2, 1, 96, 96, &straightFormat, 0, &straightOwner));
                    Assert.AreEqual(0, backBuffer(straightOwner, &straight, &size));
                    Write(straight, 0x80ff0000, 0x8000ff00);
                    sourcePacket.Bitmap = straight;
                    ((delegate* unmanaged[Stdcall]<nint, uint>)(*(void***)straight)[1])(straight);
                    Assert.AreEqual(0, send(&sourcePacket, (uint)sizeof(BitmapSourcePacket), 0, channel));
                    Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                    draw.Width = 1;
                    Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
                    Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                    Write(output, 0xff0000ff, 0xff0000ff);
                    nint conversionLock = 0;
                    try
                    {
                        Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, nint, uint, nint*, int>)(*(void***)straight)[8])(straight, 0, 2, &conversionLock));
                        Assert.AreEqual(unchecked((int)0x88982F0D), present(connection));
                        Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
                        new Span<byte>(clipPacket, 72).Clear();
                        *(uint*)clipPacket = 0x79; *(uint*)(clipPacket + 4) = clipGeometry;
                        Assert.AreEqual(0, send(clipPacket, 72, 0, channel));
                        binding[0] = 0x1f; binding[1] = visual; binding[2] = clipGeometry;
                        Assert.AreEqual(0, send(binding, 12, 0, channel));
                        draw.X = 0.5;
                        Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
                        Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                        Assert.AreEqual(0, present(connection));
                        Assert.AreEqual((0xff0000ffu, 0xff0000ffu), Read(output));
                        binding[2] = 0; draw.X = 0;
                        Assert.AreEqual(0, send(binding, 12, 0, channel));
                        Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
                        Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                        Assert.AreEqual(unchecked((int)0x88982F0D), present(connection));
                    }
                    finally { Release(conversionLock); }
                    Release(straight); straight = 0;
                    Release(straightOwner); straightOwner = 0;
                    Write(output, 0xff0000ff, 0xff0000ff);
                    Assert.AreEqual(0, present(connection));
                    Assert.AreEqual((0xff40407fu, 0xff0000ffu), Read(output));
                    draw.Width = 2;
                    Assert.AreEqual(0, send(&draw, (uint)sizeof(DrawPacket), 0, channel));
                    Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                    Write(output, 0xff0000ff, 0xff0000ff);
                    Assert.AreEqual(0, present(connection));
                    Assert.AreEqual((0xff80007fu, 0xff00807fu), Read(output));
                }
                finally { Release(straight); Release(straightOwner); }
                sourcePacket.Bitmap = back;
                ((delegate* unmanaged[Stdcall]<nint, uint>)(*(void***)back)[1])(back);
                Assert.AreEqual(0, send(&sourcePacket, (uint)sizeof(BitmapSourcePacket), 0, channel));
                Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
                Release(back); back = 0;
                Release(owner); owner = 0;
            }
            finally
            {
                Release(sourceLock); Release(replacement); Release(replacementTarget);
            }
            Release(target); target = 0;
            Assert.AreEqual(0, present(connection));
            if (removeRootChannel)
            {
                nint shared = 0, heldLock = 0;
                try
                {
                    Assert.AreEqual(0, createChannel(connection, channel, &shared));
                    Assert.AreEqual(0, destroyChannel(channel)); channel = 0;
                    Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, nint, uint, nint*, int>)(*(void***)output)[8])(output, 0, 2, &heldLock));
                    Assert.AreEqual(0, present(connection));
                }
                finally
                {
                    Release(heldLock);
                    if (shared != 0) destroyChannel(shared);
                }
            }
            else
            {
                Assert.AreEqual(0, destroyChannel(channel)); channel = 0;
            }
            Assert.AreEqual((0xff0000ffu, 0xff00ff00u), Read(output));
        }
        finally
        {
            if (channel != 0) destroyChannel(channel);
            if (connection != 0) disconnect(connection);
            Release(output); Release(back); Release(owner); Release(target); Release(factory);
        }
    }

    private static void VerifySharedTarget(nint connection, nint sourceChannel, uint visual, nint factory, nint firstOutput)
    {
        string path = typeof(CompositionTests).Assembly.GetCustomAttributes<AssemblyMetadataAttribute>().Single(a => a.Key == "AotDllPath").Value!;
        nint module = NativeLibrary.Load(path);
        var createChannel = (delegate* unmanaged[Stdcall]<nint, nint, nint*, int>)NativeLibrary.GetExport(module, "MilConnection_CreateChannel");
        var destroy = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "MilConnection_DestroyChannel");
        var duplicate = (delegate* unmanaged[Stdcall]<nint, uint, nint, uint*, int>)NativeLibrary.GetExport(module, "MilResource_DuplicateHandle");
        var createResource = (delegate* unmanaged[Stdcall]<nint, uint, uint*, int>)NativeLibrary.GetExport(module, "MilResource_CreateOrAddRefOnChannel");
        var send = (delegate* unmanaged[Stdcall]<void*, uint, byte, nint, int>)NativeLibrary.GetExport(module, "MilResource_SendCommand");
        var close = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "MilChannel_CloseBatch");
        var commit = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "MilChannel_CommitChannel");
        var present = (delegate* unmanaged[Stdcall]<nint, int>)NativeLibrary.GetExport(module, "WgxConnection_SameThreadPresent");
        var createTarget = (delegate* unmanaged[Stdcall]<nint, uint, uint, uint, float, float, uint, nint*, int>)NativeLibrary.GetExport(module, "MILFactoryCreateBitmapRenderTarget");
        var getBitmap = (delegate* unmanaged[Stdcall]<nint, nint*, int>)NativeLibrary.GetExport(module, "MILRenderTargetBitmapGetBitmap");
        var releaseResource = (delegate* unmanaged[Stdcall]<nint, uint, int*, int>)NativeLibrary.GetExport(module, "MilResource_ReleaseOnChannel");
        nint channel = 0, target = 0, output = 0, heldLock = 0;
        try
        {
            Assert.AreEqual(0, createChannel(connection, sourceChannel, &channel));
            uint sharedVisual = 0, destination = 0;
            Assert.AreEqual(0, duplicate(sourceChannel, visual, channel, &sharedVisual));
            Assert.AreEqual(0, close(sourceChannel)); Assert.AreEqual(0, commit(sourceChannel));
            Assert.AreEqual(0, createTarget(factory, 2, 1, 16, 96, 96, 1, &target));
            Assert.AreEqual(0, getBitmap(target, &output));
            Assert.AreEqual(0, createResource(channel, 47, &destination));
            TargetPacket packet = new() { Type = 0x34, Handle = destination, Target = (ulong)target, Width = 2, Height = 1 };
            Assert.AreEqual(0, send(&packet, (uint)sizeof(TargetPacket), 0, channel));
            uint* binding = stackalloc uint[] { 0x35, destination, sharedVisual };
            Assert.AreEqual(0, send(binding, 12, 0, channel));
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Release(target); target = 0;
            Write(firstOutput, 0, 0);
            Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, nint, uint, nint*, int>)(*(void***)output)[8])(output, 0, 2, &heldLock));
            Assert.AreEqual(unchecked((int)0x88982F0D), present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(firstOutput));
            Release(heldLock); heldLock = 0;
            Assert.AreEqual((0u, 0u), Read(output));
            Assert.AreEqual(0, present(connection));
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
            int deleted = 0;
            Assert.AreEqual(0, releaseResource(channel, destination, &deleted));
            Assert.AreEqual(1, deleted);
            Assert.AreEqual(0, close(channel)); Assert.AreEqual(0, commit(channel));
            Assert.AreEqual(0, destroy(channel)); channel = 0;
            Assert.AreEqual((0xffff0000u, 0xff00ff00u), Read(output));
        }
        finally
        {
            Release(heldLock);
            if (channel != 0) destroy(channel);
            Release(output); Release(target);
        }
    }

    private static void Write(nint bitmap, uint first, uint second)
    {
        nint bitmapLock = 0;
        try
        {
            Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, nint, uint, nint*, int>)(*(void***)bitmap)[8])(bitmap, 0, 2, &bitmapLock));
            uint size; uint* pixels;
            Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, uint*, uint**, int>)(*(void***)bitmapLock)[5])(bitmapLock, &size, &pixels));
            pixels[0] = first; pixels[1] = second;
        }
        finally { Release(bitmapLock); }
    }
    private static (uint, uint) Read(nint bitmap)
    {
        uint* pixels = stackalloc uint[2];
        Assert.AreEqual(0, ((delegate* unmanaged[Stdcall]<nint, nint, uint, uint, uint*, int>)(*(void***)bitmap)[7])(bitmap, 0, 8, 8, pixels));
        return (pixels[0], pixels[1]);
    }
    private static void Release(nint value) { if (value != 0) ((delegate* unmanaged[Stdcall]<nint, uint>)(*(void***)value)[2])(value); }
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    private struct TargetPacket { internal uint Type, Handle; internal ulong Window, Target; internal uint Width, Height, Dummy; }
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    private struct ImagePacket { internal uint Type, Handle; internal ulong Bitmap; internal int Back; }
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    private struct CopyPacket { internal uint Type, Handle; internal ulong Event; }
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    private struct BitmapSourcePacket { internal uint Type, Handle; internal nint Bitmap; }
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    private struct AlphaPacket { internal uint Type, Handle; internal double Alpha; }
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    private struct DrawPacket { internal uint Type, Handle, DataSize, RecordSize, Command; internal double X, Y, Width, Height; internal uint Image, Padding; }
}
