//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIAutomationTypes.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIAutomationTypes.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The target element corresponds to UI that is no longer available (for example, the parent window has closed). 的本地化字符串。
        /// </summary>
        internal static string ElementNotAvailable {
            get {
                return ResourceManager.GetString("ElementNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation is not allowed on a nonenabled element. 的本地化字符串。
        /// </summary>
        internal static string ElementNotEnabled {
            get {
                return ResourceManager.GetString("ElementNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 button 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeButton {
            get {
                return ResourceManager.GetString("LocalizedControlTypeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 calendar 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeCalendar {
            get {
                return ResourceManager.GetString("LocalizedControlTypeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 check box 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeCheckBox {
            get {
                return ResourceManager.GetString("LocalizedControlTypeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 combo box 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeComboBox {
            get {
                return ResourceManager.GetString("LocalizedControlTypeComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 custom 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeCustom {
            get {
                return ResourceManager.GetString("LocalizedControlTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 datagrid 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeDataGrid {
            get {
                return ResourceManager.GetString("LocalizedControlTypeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dataitem 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeDataItem {
            get {
                return ResourceManager.GetString("LocalizedControlTypeDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 document 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeDocument {
            get {
                return ResourceManager.GetString("LocalizedControlTypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 edit 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeEdit {
            get {
                return ResourceManager.GetString("LocalizedControlTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 group 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeGroup {
            get {
                return ResourceManager.GetString("LocalizedControlTypeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 header 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeHeader {
            get {
                return ResourceManager.GetString("LocalizedControlTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 header item 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeHeaderItem {
            get {
                return ResourceManager.GetString("LocalizedControlTypeHeaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hyperlink 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeHyperlink {
            get {
                return ResourceManager.GetString("LocalizedControlTypeHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 image 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeImage {
            get {
                return ResourceManager.GetString("LocalizedControlTypeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 list item 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeListItem {
            get {
                return ResourceManager.GetString("LocalizedControlTypeListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 list view 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeListView {
            get {
                return ResourceManager.GetString("LocalizedControlTypeListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeMenu {
            get {
                return ResourceManager.GetString("LocalizedControlTypeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu bar 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeMenuBar {
            get {
                return ResourceManager.GetString("LocalizedControlTypeMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu item 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeMenuItem {
            get {
                return ResourceManager.GetString("LocalizedControlTypeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pane 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypePane {
            get {
                return ResourceManager.GetString("LocalizedControlTypePane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 progress bar 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeProgressBar {
            get {
                return ResourceManager.GetString("LocalizedControlTypeProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 radio button 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeRadioButton {
            get {
                return ResourceManager.GetString("LocalizedControlTypeRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 scroll bar 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeScrollBar {
            get {
                return ResourceManager.GetString("LocalizedControlTypeScrollBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 separator 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeSeparator {
            get {
                return ResourceManager.GetString("LocalizedControlTypeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 slider 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeSlider {
            get {
                return ResourceManager.GetString("LocalizedControlTypeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 spinner 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeSpinner {
            get {
                return ResourceManager.GetString("LocalizedControlTypeSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 split button 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeSplitButton {
            get {
                return ResourceManager.GetString("LocalizedControlTypeSplitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 status bar 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeStatusBar {
            get {
                return ResourceManager.GetString("LocalizedControlTypeStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tab 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeTab {
            get {
                return ResourceManager.GetString("LocalizedControlTypeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tab item 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeTabItem {
            get {
                return ResourceManager.GetString("LocalizedControlTypeTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 table 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeTable {
            get {
                return ResourceManager.GetString("LocalizedControlTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 text 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeText {
            get {
                return ResourceManager.GetString("LocalizedControlTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 thumb 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeThumb {
            get {
                return ResourceManager.GetString("LocalizedControlTypeThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 title bar 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeTitleBar {
            get {
                return ResourceManager.GetString("LocalizedControlTypeTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tool bar 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeToolBar {
            get {
                return ResourceManager.GetString("LocalizedControlTypeToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tool tip 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeToolTip {
            get {
                return ResourceManager.GetString("LocalizedControlTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tree view 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeTreeView {
            get {
                return ResourceManager.GetString("LocalizedControlTypeTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tree view item 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeTreeViewItem {
            get {
                return ResourceManager.GetString("LocalizedControlTypeTreeViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 window 的本地化字符串。
        /// </summary>
        internal static string LocalizedControlTypeWindow {
            get {
                return ResourceManager.GetString("LocalizedControlTypeWindow", resourceCulture);
            }
        }
    }
}
