//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Input.Manipulations.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Input.Manipulations.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Value of {0} is outside of the allowed range. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of {0} cannot be changed while the inertia processor is running. 的本地化字符串。
        /// </summary>
        internal static string CannotChangeParameterDuringInertia {
            get {
                return ResourceManager.GetString("CannotChangeParameterDuringInertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of {0} must be either NaN, or a finite value greater than or equal to 1. 的本地化字符串。
        /// </summary>
        internal static string IllegalPivotRadius {
            get {
                return ResourceManager.GetString("IllegalPivotRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Either {0}, or {1} and {2}, needs to be specified. 的本地化字符串。
        /// </summary>
        internal static string InertiaParametersUnspecified1and2 {
            get {
                return ResourceManager.GetString("InertiaParametersUnspecified1and2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Either {0} or {1} needs to be specified. 的本地化字符串。
        /// </summary>
        internal static string InertiaParametersUnspecified2 {
            get {
                return ResourceManager.GetString("InertiaParametersUnspecified2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitialRadius should be a finite number, greater than or equal to 1. 的本地化字符串。
        /// </summary>
        internal static string InertiaProcessorInvalidRadius {
            get {
                return ResourceManager.GetString("InertiaProcessorInvalidRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp values must not decrease. 的本地化字符串。
        /// </summary>
        internal static string InvalidTimestamp {
            get {
                return ResourceManager.GetString("InvalidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one of the following must be specified: linear velocity ({0} or {1}), angular velocity ({2}), or expansion velocity ({3} or {4}). 的本地化字符串。
        /// </summary>
        internal static string NoInertiaVelocitiesSpecified {
            get {
                return ResourceManager.GetString("NoInertiaVelocitiesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently, only proportional expansion is supported. {0} must equal {1}. 的本地化字符串。
        /// </summary>
        internal static string OnlyProportionalExpansionSupported {
            get {
                return ResourceManager.GetString("OnlyProportionalExpansionSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of {0} must be finite. 的本地化字符串。
        /// </summary>
        internal static string ValueMustBeFinite {
            get {
                return ResourceManager.GetString("ValueMustBeFinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of {0} must be finite and non-negative. 的本地化字符串。
        /// </summary>
        internal static string ValueMustBeFiniteNonNegative {
            get {
                return ResourceManager.GetString("ValueMustBeFiniteNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of {0} must be finite or NaN. 的本地化字符串。
        /// </summary>
        internal static string ValueMustBeFiniteOrNaN {
            get {
                return ResourceManager.GetString("ValueMustBeFiniteOrNaN", resourceCulture);
            }
        }
    }
}
